export interface Player {
  player_id: number;
  name: string;
  position: string;
  team: string;
  adp: number;
  adp_formatted: string;
  times_drafted: number;
  high: number;
  low: number;
  stdev: number;
  bye: number;
}

export interface PlayersResponse {
  status: string;
  meta: {
    type: string;
    teams: number;
    rounds: number;
    total_drafts: number;
    start_date: string;
    end_date: string;
  };
  players: Player[];
}

export const players = {
  status: 'Success',
  meta: {
    type: 'Half-PPR',
    teams: 12,
    rounds: 15,
    total_drafts: 4576,
    start_date: '2023-08-28',
    end_date: '2023-09-01',
  },
  players: [
    {
      player_id: 4876,
      name: 'Justin Jefferson',
      position: 'WR',
      team: 'MIN',
      adp: 1.4,
      adp_formatted: '1.01',
      times_drafted: 603,
      high: 1,
      low: 8,
      stdev: 0.7,
      bye: 6,
    },
    {
      player_id: 2434,
      name: 'Christian McCaffrey',
      position: 'RB',
      team: 'SF',
      adp: 2.3,
      adp_formatted: '1.02',
      times_drafted: 712,
      high: 1,
      low: 12,
      stdev: 1.0,
      bye: 9,
    },
    {
      player_id: 2625,
      name: 'Austin Ekeler',
      position: 'RB',
      team: 'LAC',
      adp: 2.5,
      adp_formatted: '1.03',
      times_drafted: 152,
      high: 1,
      low: 17,
      stdev: 2.0,
      bye: 5,
    },
    {
      player_id: 2390,
      name: 'Tyreek Hill',
      position: 'WR',
      team: 'MIA',
      adp: 4.6,
      adp_formatted: '1.05',
      times_drafted: 439,
      high: 1,
      low: 32,
      stdev: 2.2,
      bye: 6,
    },
    {
      player_id: 1989,
      name: 'Travis Kelce',
      position: 'TE',
      team: 'KC',
      adp: 5.3,
      adp_formatted: '1.05',
      times_drafted: 461,
      high: 1,
      low: 41,
      stdev: 2.9,
      bye: 6,
    },
    {
      player_id: 5177,
      name: "Ja'Marr Chase",
      position: 'WR',
      team: 'CIN',
      adp: 5.6,
      adp_formatted: '1.06',
      times_drafted: 1432,
      high: 1,
      low: 65,
      stdev: 2.5,
      bye: 12,
    },
    {
      player_id: 2863,
      name: 'Nick Chubb',
      position: 'RB',
      team: 'CLE',
      adp: 6.0,
      adp_formatted: '1.06',
      times_drafted: 540,
      high: 1,
      low: 56,
      stdev: 3.5,
      bye: 10,
    },
    {
      player_id: 5670,
      name: 'Bijan Robinson',
      position: 'RB',
      team: 'ATL',
      adp: 7.4,
      adp_formatted: '1.07',
      times_drafted: 813,
      high: 1,
      low: 80,
      stdev: 3.9,
      bye: 12,
    },
    {
      player_id: 2449,
      name: 'Cooper Kupp',
      position: 'WR',
      team: 'LAR',
      adp: 8.9,
      adp_formatted: '1.09',
      times_drafted: 696,
      high: 1,
      low: 89,
      stdev: 4.5,
      bye: 6,
    },
    {
      player_id: 2860,
      name: 'Saquon Barkley',
      position: 'RB',
      team: 'NYG',
      adp: 9.7,
      adp_formatted: '1.10',
      times_drafted: 755,
      high: 1,
      low: 104,
      stdev: 4.9,
      bye: 11,
    },
    {
      player_id: 2316,
      name: 'Stefon Diggs',
      position: 'WR',
      team: 'BUF',
      adp: 11.1,
      adp_formatted: '1.11',
      times_drafted: 751,
      high: 1,
      low: 113,
      stdev: 5.6,
      bye: 12,
    },
    {
      player_id: 2350,
      name: 'Derrick Henry',
      position: 'RB',
      team: 'TEN',
      adp: 12.6,
      adp_formatted: '1.13',
      times_drafted: 495,
      high: 1,
      low: 128,
      stdev: 7.3,
      bye: 5,
    },
    {
      player_id: 3435,
      name: 'Tony Pollard',
      position: 'RB',
      team: 'DAL',
      adp: 13.5,
      adp_formatted: '1.14',
      times_drafted: 960,
      high: 1,
      low: 152,
      stdev: 6.1,
      bye: 7,
    },
    {
      player_id: 3247,
      name: 'A.J. Brown',
      position: 'WR',
      team: 'PHI',
      adp: 13.6,
      adp_formatted: '1.14',
      times_drafted: 541,
      high: 1,
      low: 137,
      stdev: 6.2,
      bye: 5,
    },
    {
      player_id: 4869,
      name: 'CeeDee Lamb',
      position: 'WR',
      team: 'DAL',
      adp: 15.4,
      adp_formatted: '2.01',
      times_drafted: 715,
      high: 1,
      low: 171,
      stdev: 8.9,
      bye: 7,
    },
    {
      player_id: 5182,
      name: 'Amon-Ra St. Brown',
      position: 'WR',
      team: 'DET',
      adp: 17.1,
      adp_formatted: '2.03',
      times_drafted: 794,
      high: 1,
      low: 176,
      stdev: 8.2,
      bye: 5,
    },
    {
      player_id: 2125,
      name: 'Davante Adams',
      position: 'WR',
      team: 'LV',
      adp: 17.3,
      adp_formatted: '2.03',
      times_drafted: 551,
      high: 1,
      low: 176,
      stdev: 10.4,
      bye: 10,
    },
    {
      player_id: 5548,
      name: 'Garrett Wilson',
      position: 'WR',
      team: 'NYJ',
      adp: 17.3,
      adp_formatted: '2.03',
      times_drafted: 1066,
      high: 1,
      low: 175,
      stdev: 6.8,
      bye: 12,
    },
    {
      player_id: 2462,
      name: 'Patrick Mahomes',
      position: 'QB',
      team: 'KC',
      adp: 18.4,
      adp_formatted: '2.04',
      times_drafted: 444,
      high: 1,
      low: 177,
      stdev: 11.0,
      bye: 6,
    },
    {
      player_id: 3255,
      name: 'Josh Jacobs',
      position: 'RB',
      team: 'LV',
      adp: 19.1,
      adp_formatted: '2.05',
      times_drafted: 1107,
      high: 1,
      low: 178,
      stdev: 8.2,
      bye: 10,
    },
    {
      player_id: 5178,
      name: 'Jaylen Waddle',
      position: 'WR',
      team: 'MIA',
      adp: 22.8,
      adp_formatted: '2.09',
      times_drafted: 536,
      high: 1,
      low: 177,
      stdev: 12.0,
      bye: 6,
    },
    {
      player_id: 5544,
      name: 'Chris Olave',
      position: 'WR',
      team: 'NO',
      adp: 23.2,
      adp_formatted: '2.09',
      times_drafted: 716,
      high: 1,
      low: 160,
      stdev: 9.0,
      bye: 12,
    },
    {
      player_id: 4864,
      name: 'Jonathan Taylor',
      position: 'RB',
      team: 'IND',
      adp: 24.8,
      adp_formatted: '2.11',
      times_drafted: 215,
      high: 1,
      low: 153,
      stdev: 18.1,
      bye: 14,
    },
    {
      player_id: 2885,
      name: 'Josh Allen',
      position: 'QB',
      team: 'BUF',
      adp: 25.1,
      adp_formatted: '2.11',
      times_drafted: 576,
      high: 1,
      low: 161,
      stdev: 10.5,
      bye: 12,
    },
    {
      player_id: 5210,
      name: 'Rhamondre Stevenson',
      position: 'RB',
      team: 'NE',
      adp: 25.5,
      adp_formatted: '2.11',
      times_drafted: 368,
      high: 1,
      low: 175,
      stdev: 13.7,
      bye: 14,
    },
    {
      player_id: 5025,
      name: 'Jalen Hurts',
      position: 'QB',
      team: 'PHI',
      adp: 25.7,
      adp_formatted: '2.12',
      times_drafted: 703,
      high: 1,
      low: 174,
      stdev: 9.8,
      bye: 5,
    },
    {
      player_id: 4872,
      name: 'Najee Harris',
      position: 'RB',
      team: 'PIT',
      adp: 27.1,
      adp_formatted: '2.13',
      times_drafted: 497,
      high: 1,
      low: 171,
      stdev: 12.1,
      bye: 9,
    },
    {
      player_id: 4863,
      name: 'Travis Etienne',
      position: 'RB',
      team: 'JAX',
      adp: 28.4,
      adp_formatted: '2.14',
      times_drafted: 721,
      high: 14,
      low: 163,
      stdev: 9.2,
      bye: 12,
    },
    {
      player_id: 4870,
      name: 'Tee Higgins',
      position: 'WR',
      team: 'CIN',
      adp: 28.5,
      adp_formatted: '3.01',
      times_drafted: 416,
      high: 1,
      low: 168,
      stdev: 11.9,
      bye: 12,
    },
    {
      player_id: 4883,
      name: 'DeVonta Smith',
      position: 'WR',
      team: 'PHI',
      adp: 30.1,
      adp_formatted: '3.02',
      times_drafted: 848,
      high: 17,
      low: 134,
      stdev: 7.1,
      bye: 5,
    },
    {
      player_id: 2438,
      name: 'Joe Mixon',
      position: 'RB',
      team: 'CIN',
      adp: 31.0,
      adp_formatted: '3.03',
      times_drafted: 1079,
      high: 16,
      low: 129,
      stdev: 5.5,
      bye: 12,
    },
    {
      player_id: 5503,
      name: 'Breece Hall',
      position: 'RB',
      team: 'NYJ',
      adp: 31.1,
      adp_formatted: '3.03',
      times_drafted: 198,
      high: 21,
      low: 142,
      stdev: 10.0,
      bye: 12,
    },
    {
      player_id: 2277,
      name: 'Amari Cooper',
      position: 'WR',
      team: 'CLE',
      adp: 31.2,
      adp_formatted: '3.03',
      times_drafted: 300,
      high: 9,
      low: 131,
      stdev: 8.5,
      bye: 10,
    },
    {
      player_id: 2872,
      name: 'Mark Andrews',
      position: 'TE',
      team: 'BAL',
      adp: 32.3,
      adp_formatted: '3.04',
      times_drafted: 863,
      high: 17,
      low: 127,
      stdev: 5.7,
      bye: 14,
    },
    {
      player_id: 3246,
      name: 'Deebo Samuel',
      position: 'WR',
      team: 'SF',
      adp: 33.5,
      adp_formatted: '3.05',
      times_drafted: 425,
      high: 21,
      low: 138,
      stdev: 7.2,
      bye: 9,
    },
    {
      player_id: 3239,
      name: 'D.K. Metcalf',
      position: 'WR',
      team: 'SEA',
      adp: 35.1,
      adp_formatted: '3.07',
      times_drafted: 568,
      high: 21,
      low: 96,
      stdev: 5.4,
      bye: 10,
    },
    {
      player_id: 2507,
      name: 'Aaron Jones',
      position: 'RB',
      team: 'GB',
      adp: 35.8,
      adp_formatted: '3.08',
      times_drafted: 844,
      high: 23,
      low: 46,
      stdev: 4.8,
      bye: 10,
    },
    {
      player_id: 2888,
      name: 'Lamar Jackson',
      position: 'QB',
      team: 'BAL',
      adp: 35.9,
      adp_formatted: '3.08',
      times_drafted: 553,
      high: 20,
      low: 95,
      stdev: 5.8,
      bye: 14,
    },
    {
      player_id: 2866,
      name: 'Calvin Ridley',
      position: 'WR',
      team: 'JAX',
      adp: 36.1,
      adp_formatted: '3.08',
      times_drafted: 1295,
      high: 18,
      low: 179,
      stdev: 10.5,
      bye: 12,
    },
    {
      player_id: 5672,
      name: 'Jahmyr Gibbs',
      position: 'RB',
      team: 'DET',
      adp: 36.1,
      adp_formatted: '3.08',
      times_drafted: 1271,
      high: 21,
      low: 50,
      stdev: 5.7,
      bye: 5,
    },
    {
      player_id: 5625,
      name: 'Kenneth Walker III',
      position: 'RB',
      team: 'SEA',
      adp: 39.5,
      adp_formatted: '3.11',
      times_drafted: 499,
      high: 24,
      low: 52,
      stdev: 5.9,
      bye: 10,
    },
    {
      player_id: 4882,
      name: 'Joe Burrow',
      position: 'QB',
      team: 'CIN',
      adp: 40.9,
      adp_formatted: '3.13',
      times_drafted: 515,
      high: 25,
      low: 84,
      stdev: 6.0,
      bye: 12,
    },
    {
      player_id: 2876,
      name: 'D.J. Moore',
      position: 'WR',
      team: 'CHI',
      adp: 41.7,
      adp_formatted: '3.14',
      times_drafted: 643,
      high: 30,
      low: 54,
      stdev: 4.5,
      bye: 7,
    },
    {
      player_id: 1992,
      name: 'Keenan Allen',
      position: 'WR',
      team: 'LAC',
      adp: 42.7,
      adp_formatted: '4.01',
      times_drafted: 701,
      high: 30,
      low: 55,
      stdev: 4.7,
      bye: 5,
    },
    {
      player_id: 4887,
      name: 'Justin Herbert',
      position: 'QB',
      team: 'LAC',
      adp: 44.9,
      adp_formatted: '4.03',
      times_drafted: 618,
      high: 29,
      low: 116,
      stdev: 6.0,
      bye: 5,
    },
    {
      player_id: 4861,
      name: 'Jerry Jeudy',
      position: 'WR',
      team: 'DEN',
      adp: 45.4,
      adp_formatted: '4.03',
      times_drafted: 97,
      high: 29,
      low: 60,
      stdev: 6.0,
      bye: 14,
    },
    {
      player_id: 3252,
      name: 'Miles Sanders',
      position: 'RB',
      team: 'CAR',
      adp: 45.9,
      adp_formatted: '4.04',
      times_drafted: 315,
      high: 31,
      low: 92,
      stdev: 5.6,
      bye: 11,
    },
    {
      player_id: 4888,
      name: 'J.K. Dobbins',
      position: 'RB',
      team: 'BAL',
      adp: 46.0,
      adp_formatted: '4.04',
      times_drafted: 398,
      high: 33,
      low: 59,
      stdev: 4.6,
      bye: 14,
    },
    {
      player_id: 5191,
      name: 'Justin Fields',
      position: 'QB',
      team: 'CHI',
      adp: 47.7,
      adp_formatted: '4.06',
      times_drafted: 587,
      high: 28,
      low: 164,
      stdev: 7.3,
      bye: 7,
    },
    {
      player_id: 4881,
      name: 'Cam Akers',
      position: 'RB',
      team: 'MIN',
      adp: 48.6,
      adp_formatted: '4.07',
      times_drafted: 315,
      high: 34,
      low: 77,
      stdev: 5.5,
      bye: 6,
    },
    {
      player_id: 5360,
      name: 'Christian Watson',
      position: 'WR',
      team: 'GB',
      adp: 49.1,
      adp_formatted: '4.07',
      times_drafted: 569,
      high: 34,
      low: 95,
      stdev: 5.5,
      bye: 10,
    },
    {
      player_id: 3458,
      name: 'Alexander Mattison',
      position: 'RB',
      team: 'MIN',
      adp: 50.2,
      adp_formatted: '4.08',
      times_drafted: 961,
      high: 35,
      low: 97,
      stdev: 5.5,
      bye: 6,
    },
    {
      player_id: 5632,
      name: 'Dameon Pierce',
      position: 'RB',
      team: 'HOU',
      adp: 50.7,
      adp_formatted: '4.09',
      times_drafted: 1060,
      high: 35,
      low: 71,
      stdev: 5.7,
      bye: 14,
    },
    {
      player_id: 3449,
      name: 'Terry McLaurin',
      position: 'WR',
      team: 'WAS',
      adp: 51.6,
      adp_formatted: '4.10',
      times_drafted: 336,
      high: 33,
      low: 126,
      stdev: 6.8,
      bye: 14,
    },
    {
      player_id: 3307,
      name: 'T.J. Hockenson',
      position: 'TE',
      team: 'MIN',
      adp: 52.6,
      adp_formatted: '4.11',
      times_drafted: 614,
      high: 35,
      low: 105,
      stdev: 6.7,
      bye: 6,
    },
    {
      player_id: 1975,
      name: 'DeAndre Hopkins',
      position: 'WR',
      team: 'TEN',
      adp: 52.7,
      adp_formatted: '4.11',
      times_drafted: 608,
      high: 36,
      low: 99,
      stdev: 6.1,
      bye: 5,
    },
    {
      player_id: 5186,
      name: 'Trevor Lawrence',
      position: 'QB',
      team: 'JAX',
      adp: 56.1,
      adp_formatted: '4.14',
      times_drafted: 671,
      high: 42,
      low: 116,
      stdev: 5.4,
      bye: 12,
    },
    {
      player_id: 5574,
      name: 'Drake London',
      position: 'WR',
      team: 'ATL',
      adp: 56.2,
      adp_formatted: '4.14',
      times_drafted: 469,
      high: 40,
      low: 118,
      stdev: 6.2,
      bye: 12,
    },
    {
      player_id: 2470,
      name: 'James Conner',
      position: 'RB',
      team: 'ARI',
      adp: 57.2,
      adp_formatted: '5.01',
      times_drafted: 514,
      high: 43,
      low: 106,
      stdev: 5.4,
      bye: 11,
    },
    {
      player_id: 4891,
      name: 'Brandon Aiyuk',
      position: 'WR',
      team: 'SF',
      adp: 58.9,
      adp_formatted: '5.03',
      times_drafted: 577,
      high: 43,
      low: 111,
      stdev: 5.9,
      bye: 9,
    },
    {
      player_id: 2499,
      name: 'George Kittle',
      position: 'TE',
      team: 'SF',
      adp: 59.0,
      adp_formatted: '5.03',
      times_drafted: 545,
      high: 42,
      low: 83,
      stdev: 6.2,
      bye: 9,
    },
    {
      player_id: 5337,
      name: 'Isiah Pacheco',
      position: 'RB',
      team: 'KC',
      adp: 59.6,
      adp_formatted: '5.04',
      times_drafted: 501,
      high: 46,
      low: 73,
      stdev: 5.0,
      bye: 6,
    },
    {
      player_id: 2436,
      name: 'Mike Williams',
      position: 'WR',
      team: 'LAC',
      adp: 60.3,
      adp_formatted: '5.04',
      times_drafted: 448,
      high: 44,
      low: 114,
      stdev: 6.0,
      bye: 5,
    },
    {
      player_id: 3238,
      name: 'David Montgomery',
      position: 'RB',
      team: 'DET',
      adp: 62.4,
      adp_formatted: '5.06',
      times_drafted: 399,
      high: 44,
      low: 93,
      stdev: 6.8,
      bye: 5,
    },
    {
      player_id: 2304,
      name: 'Tyler Lockett',
      position: 'WR',
      team: 'SEA',
      adp: 62.7,
      adp_formatted: '5.07',
      times_drafted: 472,
      high: 45,
      low: 93,
      stdev: 6.5,
      bye: 10,
    },
    {
      player_id: 5626,
      name: 'Rachaad White',
      position: 'RB',
      team: 'TB',
      adp: 63.2,
      adp_formatted: '5.07',
      times_drafted: 646,
      high: 48,
      low: 79,
      stdev: 5.6,
      bye: 11,
    },
    {
      player_id: 2870,
      name: 'Christian Kirk',
      position: 'WR',
      team: 'JAX',
      adp: 64.0,
      adp_formatted: '5.08',
      times_drafted: 341,
      high: 47,
      low: 84,
      stdev: 6.3,
      bye: 12,
    },
    {
      player_id: 5185,
      name: 'Javonte Williams',
      position: 'RB',
      team: 'DEN',
      adp: 65.7,
      adp_formatted: '5.10',
      times_drafted: 637,
      high: 48,
      low: 83,
      stdev: 6.7,
      bye: 14,
    },
    {
      player_id: 2439,
      name: 'Alvin Kamara',
      position: 'RB',
      team: 'NO',
      adp: 66.1,
      adp_formatted: '5.10',
      times_drafted: 789,
      high: 45,
      low: 84,
      stdev: 7.9,
      bye: 12,
    },
    {
      player_id: 2111,
      name: 'Mike Evans',
      position: 'WR',
      team: 'TB',
      adp: 66.2,
      adp_formatted: '5.10',
      times_drafted: 508,
      high: 48,
      low: 83,
      stdev: 6.9,
      bye: 11,
    },
    {
      player_id: 2465,
      name: 'Chris Godwin',
      position: 'WR',
      team: 'TB',
      adp: 68.1,
      adp_formatted: '5.12',
      times_drafted: 337,
      high: 46,
      low: 86,
      stdev: 8.2,
      bye: 11,
    },
    {
      player_id: 4862,
      name: "D'Andre Swift",
      position: 'RB',
      team: 'PHI',
      adp: 69.3,
      adp_formatted: '5.13',
      times_drafted: 305,
      high: 44,
      low: 82,
      stdev: 9.7,
      bye: 5,
    },
    {
      player_id: 2322,
      name: 'Darren Waller',
      position: 'TE',
      team: 'NYG',
      adp: 70.3,
      adp_formatted: '5.14',
      times_drafted: 1501,
      high: 43,
      low: 95,
      stdev: 10.4,
      bye: 11,
    },
    {
      player_id: 3249,
      name: 'Marquise Brown',
      position: 'WR',
      team: 'ARI',
      adp: 70.8,
      adp_formatted: '6.01',
      times_drafted: 162,
      high: 29,
      low: 93,
      stdev: 16.0,
      bye: 11,
    },
    {
      player_id: 2444,
      name: 'Deshaun Watson',
      position: 'QB',
      team: 'CLE',
      adp: 71.3,
      adp_formatted: '6.01',
      times_drafted: 241,
      high: 48,
      low: 180,
      stdev: 18.4,
      bye: 10,
    },
    {
      player_id: 3419,
      name: 'Diontae Johnson',
      position: 'WR',
      team: 'PIT',
      adp: 71.4,
      adp_formatted: '6.01',
      times_drafted: 736,
      high: 47,
      low: 91,
      stdev: 9.1,
      bye: 9,
    },
    {
      player_id: 5652,
      name: 'James Cook',
      position: 'RB',
      team: 'BUF',
      adp: 71.6,
      adp_formatted: '6.02',
      times_drafted: 1056,
      high: 48,
      low: 89,
      stdev: 8.9,
      bye: 12,
    },
    {
      player_id: 5181,
      name: 'Kyle Pitts',
      position: 'TE',
      team: 'ATL',
      adp: 73.5,
      adp_formatted: '6.04',
      times_drafted: 491,
      high: 45,
      low: 91,
      stdev: 10.7,
      bye: 12,
    },
    {
      player_id: 4880,
      name: 'Michael Pittman Jr.',
      position: 'WR',
      team: 'IND',
      adp: 75.7,
      adp_formatted: '6.06',
      times_drafted: 273,
      high: 45,
      low: 94,
      stdev: 11.5,
      bye: 14,
    },
    {
      player_id: 5576,
      name: 'George Pickens',
      position: 'WR',
      team: 'PIT',
      adp: 76.5,
      adp_formatted: '6.06',
      times_drafted: 960,
      high: 53,
      low: 97,
      stdev: 8.7,
      bye: 9,
    },
    {
      player_id: 2377,
      name: 'Dak Prescott',
      position: 'QB',
      team: 'DAL',
      adp: 76.6,
      adp_formatted: '6.07',
      times_drafted: 223,
      high: 46,
      low: 99,
      stdev: 11.7,
      bye: 7,
    },
    {
      player_id: 5578,
      name: 'Jahan Dotson',
      position: 'WR',
      team: 'WAS',
      adp: 78.8,
      adp_formatted: '6.09',
      times_drafted: 717,
      high: 57,
      low: 95,
      stdev: 8.3,
      bye: 14,
    },
    {
      player_id: 5605,
      name: 'Brian Robinson Jr.',
      position: 'RB',
      team: 'WAS',
      adp: 79.5,
      adp_formatted: '6.09',
      times_drafted: 413,
      high: 57,
      low: 92,
      stdev: 8.4,
      bye: 14,
    },
    {
      player_id: 4890,
      name: 'Tua Tagovailoa',
      position: 'QB',
      team: 'MIA',
      adp: 81.2,
      adp_formatted: '6.11',
      times_drafted: 324,
      high: 54,
      low: 127,
      stdev: 10.1,
      bye: 6,
    },
    {
      player_id: 2896,
      name: 'Dallas Goedert',
      position: 'TE',
      team: 'PHI',
      adp: 82.4,
      adp_formatted: '6.12',
      times_drafted: 518,
      high: 61,
      low: 99,
      stdev: 8.2,
      bye: 5,
    },
    {
      player_id: 5018,
      name: 'Gabriel Davis',
      position: 'WR',
      team: 'BUF',
      adp: 83.0,
      adp_formatted: '6.13',
      times_drafted: 552,
      high: 61,
      low: 115,
      stdev: 8.3,
      bye: 12,
    },
    {
      player_id: 2869,
      name: 'Rashaad Penny',
      position: 'RB',
      team: 'PHI',
      adp: 83.1,
      adp_formatted: '6.13',
      times_drafted: 148,
      high: 56,
      low: 96,
      stdev: 10.2,
      bye: 5,
    },
    {
      player_id: 4886,
      name: 'A.J. Dillon',
      position: 'RB',
      team: 'GB',
      adp: 85.2,
      adp_formatted: '7.01',
      times_drafted: 333,
      high: 63,
      low: 103,
      stdev: 8.2,
      bye: 10,
    },
    {
      player_id: 5673,
      name: 'Jordan Addison',
      position: 'WR',
      team: 'MIN',
      adp: 85.4,
      adp_formatted: '7.01',
      times_drafted: 593,
      high: 65,
      low: 101,
      stdev: 7.5,
      bye: 6,
    },
    {
      player_id: 5008,
      name: 'Antonio Gibson',
      position: 'RB',
      team: 'WAS',
      adp: 87.6,
      adp_formatted: '7.04',
      times_drafted: 383,
      high: 68,
      low: 110,
      stdev: 7.5,
      bye: 14,
    },
    {
      player_id: 2445,
      name: 'Jamaal Williams',
      position: 'RB',
      team: 'NO',
      adp: 88.6,
      adp_formatted: '7.05',
      times_drafted: 363,
      high: 69,
      low: 107,
      stdev: 7.2,
      bye: 12,
    },
    {
      player_id: 5671,
      name: 'Jaxon Smith-Njigba',
      position: 'WR',
      team: 'SEA',
      adp: 89.5,
      adp_formatted: '7.05',
      times_drafted: 419,
      high: 69,
      low: 112,
      stdev: 7.9,
      bye: 10,
    },
    {
      player_id: 1902,
      name: 'Kirk Cousins',
      position: 'QB',
      team: 'MIN',
      adp: 90.6,
      adp_formatted: '7.07',
      times_drafted: 230,
      high: 59,
      low: 121,
      stdev: 12.0,
      bye: 6,
    },
    {
      player_id: 5546,
      name: 'Treylon Burks',
      position: 'WR',
      team: 'TEN',
      adp: 90.7,
      adp_formatted: '7.07',
      times_drafted: 130,
      high: 67,
      low: 107,
      stdev: 9.1,
      bye: 5,
    },
    {
      player_id: 2114,
      name: 'Brandin Cooks',
      position: 'WR',
      team: 'DAL',
      adp: 91.5,
      adp_formatted: '7.07',
      times_drafted: 464,
      high: 72,
      low: 106,
      stdev: 7.1,
      bye: 7,
    },
    {
      player_id: 2862,
      name: 'Courtland Sutton',
      position: 'WR',
      team: 'DEN',
      adp: 92.9,
      adp_formatted: '7.09',
      times_drafted: 572,
      high: 72,
      low: 120,
      stdev: 7.8,
      bye: 14,
    },
    {
      player_id: 2441,
      name: 'Samaje Perine',
      position: 'RB',
      team: 'DEN',
      adp: 93.9,
      adp_formatted: '7.10',
      times_drafted: 319,
      high: 74,
      low: 114,
      stdev: 7.6,
      bye: 14,
    },
    {
      player_id: 3264,
      name: 'Daniel Jones',
      position: 'QB',
      team: 'NYG',
      adp: 94.1,
      adp_formatted: '7.10',
      times_drafted: 255,
      high: 69,
      low: 116,
      stdev: 9.5,
      bye: 11,
    },
    {
      player_id: 5674,
      name: 'Quentin Johnston',
      position: 'WR',
      team: 'LAC',
      adp: 95.8,
      adp_formatted: '7.12',
      times_drafted: 229,
      high: 71,
      low: 114,
      stdev: 9.3,
      bye: 5,
    },
    {
      player_id: 3243,
      name: 'Damien Harris',
      position: 'RB',
      team: 'BUF',
      adp: 96.2,
      adp_formatted: '7.12',
      times_drafted: 146,
      high: 71,
      low: 115,
      stdev: 9.4,
      bye: 12,
    },
    {
      player_id: 5677,
      name: 'Zach Charbonnet',
      position: 'RB',
      team: 'SEA',
      adp: 97.2,
      adp_formatted: '7.13',
      times_drafted: 397,
      high: 76,
      low: 122,
      stdev: 7.8,
      bye: 10,
    },
    {
      player_id: 5188,
      name: 'Kadarius Toney',
      position: 'WR',
      team: 'KC',
      adp: 98.1,
      adp_formatted: '7.14',
      times_drafted: 315,
      high: 73,
      low: 120,
      stdev: 9.5,
      bye: 6,
    },
    {
      player_id: 5720,
      name: 'Khalil Herbert',
      position: 'RB',
      team: 'CHI',
      adp: 98.1,
      adp_formatted: '7.14',
      times_drafted: 1449,
      high: 74,
      low: 119,
      stdev: 9.3,
      bye: 7,
    },
    {
      player_id: 5193,
      name: 'Pat Freiermuth',
      position: 'TE',
      team: 'PIT',
      adp: 98.5,
      adp_formatted: '7.14',
      times_drafted: 422,
      high: 71,
      low: 129,
      stdev: 10.3,
      bye: 9,
    },
    {
      player_id: 5214,
      name: 'Elijah Mitchell',
      position: 'RB',
      team: 'SF',
      adp: 100.6,
      adp_formatted: '8.03',
      times_drafted: 189,
      high: 78,
      low: 119,
      stdev: 8.4,
      bye: 9,
    },
    {
      player_id: 1004,
      name: 'Aaron Rodgers',
      position: 'QB',
      team: 'NYJ',
      adp: 100.9,
      adp_formatted: '8.03',
      times_drafted: 588,
      high: 71,
      low: 149,
      stdev: 11.1,
      bye: 12,
    },
    {
      player_id: 5187,
      name: 'Elijah Moore',
      position: 'WR',
      team: 'CLE',
      adp: 101.4,
      adp_formatted: '8.03',
      times_drafted: 349,
      high: 79,
      low: 120,
      stdev: 8.2,
      bye: 10,
    },
    {
      player_id: 1980,
      name: 'Geno Smith',
      position: 'QB',
      team: 'SEA',
      adp: 104.1,
      adp_formatted: '8.06',
      times_drafted: 290,
      high: 79,
      low: 130,
      stdev: 9.5,
      bye: 10,
    },
    {
      player_id: 5675,
      name: 'Zay Flowers',
      position: 'WR',
      team: 'BAL',
      adp: 104.8,
      adp_formatted: '8.07',
      times_drafted: 914,
      high: 82,
      low: 139,
      stdev: 8.6,
      bye: 14,
    },
    {
      player_id: 5180,
      name: 'Rashod Bateman',
      position: 'WR',
      team: 'BAL',
      adp: 106.1,
      adp_formatted: '8.08',
      times_drafted: 164,
      high: 82,
      low: 123,
      stdev: 8.9,
      bye: 14,
    },
    {
      player_id: 2357,
      name: 'Michael Thomas',
      position: 'WR',
      team: 'NO',
      adp: 107.0,
      adp_formatted: '8.09',
      times_drafted: 588,
      high: 82,
      low: 144,
      stdev: 9.3,
      bye: 12,
    },
    {
      player_id: 2451,
      name: 'Evan Engram',
      position: 'TE',
      team: 'JAX',
      adp: 108.9,
      adp_formatted: '8.11',
      times_drafted: 365,
      high: 75,
      low: 143,
      stdev: 13.0,
      bye: 12,
    },
    {
      player_id: 5655,
      name: 'Tyler Allgeier',
      position: 'RB',
      team: 'ATL',
      adp: 109.2,
      adp_formatted: '8.11',
      times_drafted: 238,
      high: 86,
      low: 127,
      stdev: 8.6,
      bye: 12,
    },
    {
      player_id: 2737,
      name: 'Raheem Mostert',
      position: 'RB',
      team: 'MIA',
      adp: 110.2,
      adp_formatted: '8.12',
      times_drafted: 321,
      high: 89,
      low: 127,
      stdev: 7.9,
      bye: 6,
    },
    {
      player_id: 2977,
      name: 'Dalton Schultz',
      position: 'TE',
      team: 'HOU',
      adp: 110.4,
      adp_formatted: '8.12',
      times_drafted: 142,
      high: 72,
      low: 149,
      stdev: 14.6,
      bye: 14,
    },
    {
      player_id: 2442,
      name: 'JuJu Smith-Schuster',
      position: 'WR',
      team: 'NE',
      adp: 110.7,
      adp_formatted: '8.13',
      times_drafted: 173,
      high: 85,
      low: 150,
      stdev: 9.9,
      bye: 14,
    },
    {
      player_id: 5643,
      name: 'Jameson Williams',
      position: 'WR',
      team: 'DET',
      adp: 112.2,
      adp_formatted: '8.14',
      times_drafted: 152,
      high: 86,
      low: 146,
      stdev: 9.8,
      bye: 5,
    },
    {
      player_id: 5683,
      name: 'Devon Achane',
      position: 'RB',
      team: 'MIA',
      adp: 113.7,
      adp_formatted: '9.02',
      times_drafted: 178,
      high: 92,
      low: 146,
      stdev: 8.2,
      bye: 6,
    },
    {
      player_id: 5196,
      name: 'Kenneth Gainwell',
      position: 'RB',
      team: 'PHI',
      adp: 114.1,
      adp_formatted: '9.02',
      times_drafted: 260,
      high: 90,
      low: 140,
      stdev: 9.1,
      bye: 5,
    },
    {
      player_id: 2113,
      name: 'Odell Beckham Jr',
      position: 'WR',
      team: 'BAL',
      adp: 114.5,
      adp_formatted: '9.02',
      times_drafted: 351,
      high: 88,
      low: 145,
      stdev: 9.8,
      bye: 14,
    },
    {
      player_id: 2448,
      name: 'David Njoku',
      position: 'TE',
      team: 'CLE',
      adp: 114.5,
      adp_formatted: '9.03',
      times_drafted: 267,
      high: 80,
      low: 148,
      stdev: 12.9,
      bye: 10,
    },
    {
      player_id: 2440,
      name: 'Donta Foreman',
      position: 'RB',
      team: 'CHI',
      adp: 118.2,
      adp_formatted: '9.06',
      times_drafted: 57,
      high: 85,
      low: 134,
      stdev: 12.5,
      bye: 7,
    },
    {
      player_id: 3077,
      name: 'Allen Lazard',
      position: 'WR',
      team: 'NYJ',
      adp: 120.6,
      adp_formatted: '9.09',
      times_drafted: 235,
      high: 90,
      low: 150,
      stdev: 11.7,
      bye: 12,
    },
    {
      player_id: 2140,
      name: 'Jerick McKinnon',
      position: 'RB',
      team: 'KC',
      adp: 120.6,
      adp_formatted: '9.09',
      times_drafted: 297,
      high: 95,
      low: 149,
      stdev: 9.6,
      bye: 6,
    },
    {
      player_id: 2351,
      name: 'Jared Goff',
      position: 'QB',
      team: 'DET',
      adp: 120.7,
      adp_formatted: '9.09',
      times_drafted: 393,
      high: 87,
      low: 150,
      stdev: 12.7,
      bye: 5,
    },
    {
      player_id: 5587,
      name: 'Skyy Moore',
      position: 'WR',
      team: 'KC',
      adp: 121.7,
      adp_formatted: '9.10',
      times_drafted: 771,
      high: 95,
      low: 149,
      stdev: 10.0,
      bye: 6,
    },
    {
      player_id: 3267,
      name: 'Devin Singletary',
      position: 'RB',
      team: 'HOU',
      adp: 122.0,
      adp_formatted: '9.10',
      times_drafted: 63,
      high: 84,
      low: 147,
      stdev: 14.6,
      bye: 14,
    },
    {
      player_id: 5119,
      name: 'Darnell Mooney',
      position: 'WR',
      team: 'CHI',
      adp: 122.5,
      adp_formatted: '9.10',
      times_drafted: 125,
      high: 94,
      low: 150,
      stdev: 10.7,
      bye: 7,
    },
    {
      player_id: 1326,
      name: 'San Francisco Defense',
      position: 'DEF',
      team: 'SF',
      adp: 123.3,
      adp_formatted: '9.11',
      times_drafted: 877,
      high: 82,
      low: 157,
      stdev: 15.9,
      bye: 9,
    },
    {
      player_id: 1976,
      name: 'Cordarrelle Patterson',
      position: 'RB',
      team: 'ATL',
      adp: 125.4,
      adp_formatted: '9.13',
      times_drafted: 86,
      high: 96,
      low: 150,
      stdev: 11.1,
      bye: 12,
    },
    {
      player_id: 2431,
      name: 'Adam Thielen',
      position: 'WR',
      team: 'CAR',
      adp: 125.5,
      adp_formatted: '9.14',
      times_drafted: 310,
      high: 100,
      low: 150,
      stdev: 9.8,
      bye: 11,
    },
    {
      player_id: 5207,
      name: 'Nico Collins',
      position: 'WR',
      team: 'HOU',
      adp: 126.4,
      adp_formatted: '9.14',
      times_drafted: 311,
      high: 101,
      low: 149,
      stdev: 9.8,
      bye: 14,
    },
    {
      player_id: 1904,
      name: 'Russell Wilson',
      position: 'QB',
      team: 'DEN',
      adp: 128.1,
      adp_formatted: '10.02',
      times_drafted: 150,
      high: 92,
      low: 180,
      stdev: 13.9,
      bye: 14,
    },
    {
      player_id: 4889,
      name: 'Clyde Edwards-Helaire',
      position: 'RB',
      team: 'KC',
      adp: 128.5,
      adp_formatted: '10.02',
      times_drafted: 86,
      high: 101,
      low: 146,
      stdev: 10.5,
      bye: 6,
    },
    {
      player_id: 5443,
      name: 'Jaylen Warren',
      position: 'RB',
      team: 'PIT',
      adp: 128.8,
      adp_formatted: '10.03',
      times_drafted: 775,
      high: 98,
      low: 159,
      stdev: 11.5,
      bye: 9,
    },
    {
      player_id: 3409,
      name: 'Dawson Knox',
      position: 'TE',
      team: 'BUF',
      adp: 130.2,
      adp_formatted: '10.04',
      times_drafted: 119,
      high: 96,
      low: 151,
      stdev: 12.8,
      bye: 12,
    },
    {
      player_id: 1308,
      name: 'Dallas Defense',
      position: 'DEF',
      team: 'DAL',
      adp: 132.3,
      adp_formatted: '10.06',
      times_drafted: 294,
      high: 83,
      low: 167,
      stdev: 19.2,
      bye: 7,
    },
    {
      player_id: 4902,
      name: 'Cole Kmet',
      position: 'TE',
      team: 'CHI',
      adp: 132.7,
      adp_formatted: '10.07',
      times_drafted: 134,
      high: 94,
      low: 177,
      stdev: 14.8,
      bye: 7,
    },
    {
      player_id: 3496,
      name: 'Jakobi Meyers',
      position: 'WR',
      team: 'LV',
      adp: 132.9,
      adp_formatted: '10.07',
      times_drafted: 115,
      high: 109,
      low: 167,
      stdev: 9.0,
      bye: 10,
    },
    {
      player_id: 5453,
      name: 'Chigoziem Okonkwo',
      position: 'TE',
      team: 'TEN',
      adp: 132.9,
      adp_formatted: '10.07',
      times_drafted: 119,
      high: 100,
      low: 178,
      stdev: 12.3,
      bye: 5,
    },
    {
      player_id: 5679,
      name: 'Anthony Richardson',
      position: 'QB',
      team: 'IND',
      adp: 133.2,
      adp_formatted: '10.07',
      times_drafted: 652,
      high: 86,
      low: 181,
      stdev: 17.9,
      bye: 14,
    },
    {
      player_id: 5513,
      name: 'Zamir White',
      position: 'RB',
      team: 'LV',
      adp: 133.5,
      adp_formatted: '10.07',
      times_drafted: 76,
      high: 110,
      low: 148,
      stdev: 9.4,
      bye: 10,
    },
    {
      player_id: 2359,
      name: 'Tyler Boyd',
      position: 'WR',
      team: 'CIN',
      adp: 134.6,
      adp_formatted: '10.09',
      times_drafted: 127,
      high: 113,
      low: 153,
      stdev: 8.3,
      bye: 12,
    },
    {
      player_id: 5179,
      name: 'Rondale Moore',
      position: 'WR',
      team: 'ARI',
      adp: 135.2,
      adp_formatted: '10.09',
      times_drafted: 41,
      high: 109,
      low: 147,
      stdev: 10.1,
      bye: 11,
    },
    {
      player_id: 1962,
      name: 'Justin Tucker',
      position: 'PK',
      team: 'BAL',
      adp: 135.5,
      adp_formatted: '10.09',
      times_drafted: 1011,
      high: 83,
      low: 183,
      stdev: 20.1,
      bye: 14,
    },
    {
      player_id: 1303,
      name: 'Buffalo Defense',
      position: 'DEF',
      team: 'BUF',
      adp: 135.6,
      adp_formatted: '10.10',
      times_drafted: 230,
      high: 95,
      low: 164,
      stdev: 15.3,
      bye: 12,
    },
    {
      player_id: 5691,
      name: 'Tank Bigsby',
      position: 'RB',
      team: 'JAX',
      adp: 137.0,
      adp_formatted: '10.11',
      times_drafted: 565,
      high: 100,
      low: 180,
      stdev: 13.9,
      bye: 12,
    },
    {
      player_id: 3299,
      name: 'Kyler Murray',
      position: 'QB',
      team: 'ARI',
      adp: 137.6,
      adp_formatted: '10.12',
      times_drafted: 78,
      high: 91,
      low: 179,
      stdev: 17.9,
      bye: 11,
    },
    {
      player_id: 1323,
      name: 'Philadelphia Defense',
      position: 'DEF',
      team: 'PHI',
      adp: 139.3,
      adp_formatted: '10.13',
      times_drafted: 376,
      high: 96,
      low: 171,
      stdev: 16.3,
      bye: 5,
    },
    {
      player_id: 2988,
      name: 'Daniel Carlson',
      position: 'PK',
      team: 'LV',
      adp: 139.9,
      adp_formatted: '10.14',
      times_drafted: 113,
      high: 83,
      low: 181,
      stdev: 21.8,
      bye: 10,
    },
    {
      player_id: 2514,
      name: 'Harrison Butker',
      position: 'PK',
      team: 'KC',
      adp: 140.1,
      adp_formatted: '10.14',
      times_drafted: 173,
      high: 82,
      low: 184,
      stdev: 22.1,
      bye: 6,
    },
    {
      player_id: 3081,
      name: 'Gus Edwards',
      position: 'RB',
      team: 'BAL',
      adp: 141.3,
      adp_formatted: '11.01',
      times_drafted: 51,
      high: 109,
      low: 170,
      stdev: 12.9,
      bye: 14,
    },
    {
      player_id: 5036,
      name: 'Tyler Bass',
      position: 'PK',
      team: 'BUF',
      adp: 141.6,
      adp_formatted: '11.02',
      times_drafted: 145,
      high: 89,
      low: 182,
      stdev: 20.1,
      bye: 12,
    },
    {
      player_id: 3428,
      name: 'Hunter Renfrow',
      position: 'WR',
      team: 'LV',
      adp: 143.1,
      adp_formatted: '11.03',
      times_drafted: 44,
      high: 115,
      low: 168,
      stdev: 12.0,
      bye: 10,
    },
    {
      player_id: 2468,
      name: 'Zay Jones',
      position: 'WR',
      team: 'JAX',
      adp: 143.7,
      adp_formatted: '11.04',
      times_drafted: 86,
      high: 115,
      low: 177,
      stdev: 12.8,
      bye: 12,
    },
    {
      player_id: 1319,
      name: 'New Orleans Defense',
      position: 'DEF',
      team: 'NO',
      adp: 145.8,
      adp_formatted: '11.06',
      times_drafted: 150,
      high: 91,
      low: 184,
      stdev: 20.7,
      bye: 12,
    },
    {
      player_id: 2529,
      name: 'Jake Elliott',
      position: 'PK',
      team: 'PHI',
      adp: 145.9,
      adp_formatted: '11.06',
      times_drafted: 143,
      high: 86,
      low: 188,
      stdev: 23.0,
      bye: 5,
    },
    {
      player_id: 2527,
      name: 'Younghoe Koo',
      position: 'PK',
      team: 'ATL',
      adp: 146.3,
      adp_formatted: '11.06',
      times_drafted: 110,
      high: 85,
      low: 190,
      stdev: 23.4,
      bye: 12,
    },
    {
      player_id: 5586,
      name: 'Romeo Doubs',
      position: 'WR',
      team: 'GB',
      adp: 148.0,
      adp_formatted: '11.08',
      times_drafted: 407,
      high: 106,
      low: 181,
      stdev: 15.9,
      bye: 10,
    },
    {
      player_id: 2118,
      name: 'Derek Carr',
      position: 'QB',
      team: 'NO',
      adp: 148.7,
      adp_formatted: '11.09',
      times_drafted: 201,
      high: 99,
      low: 180,
      stdev: 18.8,
      bye: 12,
    },
    {
      player_id: 5669,
      name: 'Evan McPherson',
      position: 'PK',
      team: 'CIN',
      adp: 149.7,
      adp_formatted: '11.10',
      times_drafted: 208,
      high: 95,
      low: 191,
      stdev: 20.8,
      bye: 12,
    },
    {
      player_id: 5688,
      name: 'Dalton Kincaid',
      position: 'TE',
      team: 'BUF',
      adp: 149.9,
      adp_formatted: '11.10',
      times_drafted: 286,
      high: 97,
      low: 194,
      stdev: 20.0,
      bye: 12,
    },
    {
      player_id: 1309,
      name: 'Denver Defense',
      position: 'DEF',
      team: 'DEN',
      adp: 150.0,
      adp_formatted: '11.10',
      times_drafted: 85,
      high: 116,
      low: 183,
      stdev: 13.0,
      bye: 14,
    },
    {
      player_id: 1332,
      name: 'Baltimore Defense',
      position: 'DEF',
      team: 'BAL',
      adp: 150.2,
      adp_formatted: '11.10',
      times_drafted: 129,
      high: 109,
      low: 188,
      stdev: 17.9,
      bye: 14,
    },
    {
      player_id: 1318,
      name: 'New England Defense',
      position: 'DEF',
      team: 'NE',
      adp: 152.4,
      adp_formatted: '11.12',
      times_drafted: 189,
      high: 114,
      low: 182,
      stdev: 14.7,
      bye: 14,
    },
    {
      player_id: 2370,
      name: 'Tyler Higbee',
      position: 'TE',
      team: 'LAR',
      adp: 152.7,
      adp_formatted: '11.13',
      times_drafted: 145,
      high: 104,
      low: 180,
      stdev: 18.7,
      bye: 6,
    },
    {
      player_id: 2464,
      name: 'Gerald Everett',
      position: 'TE',
      team: 'LAC',
      adp: 153.6,
      adp_formatted: '11.14',
      times_drafted: 102,
      high: 112,
      low: 180,
      stdev: 16.7,
      bye: 5,
    },
    {
      player_id: 4873,
      name: 'Chuba Hubbard',
      position: 'RB',
      team: 'CAR',
      adp: 153.8,
      adp_formatted: '11.14',
      times_drafted: 64,
      high: 112,
      low: 179,
      stdev: 16.0,
      bye: 11,
    },
    {
      player_id: 2336,
      name: 'Brandon McManus',
      position: 'PK',
      team: 'JAX',
      adp: 154.3,
      adp_formatted: '11.14',
      times_drafted: 79,
      high: 105,
      low: 191,
      stdev: 18.6,
      bye: 12,
    },
    {
      player_id: 5695,
      name: 'Roschon Johnson',
      position: 'RB',
      team: 'CHI',
      adp: 154.6,
      adp_formatted: '12.01',
      times_drafted: 117,
      high: 100,
      low: 205,
      stdev: 21.2,
      bye: 7,
    },
    {
      player_id: 2879,
      name: 'Michael Gallup',
      position: 'WR',
      team: 'DAL',
      adp: 155.0,
      adp_formatted: '12.01',
      times_drafted: 87,
      high: 112,
      low: 180,
      stdev: 16.4,
      bye: 7,
    },
    {
      player_id: 1664,
      name: 'Matthew Stafford',
      position: 'QB',
      team: 'LAR',
      adp: 155.1,
      adp_formatted: '12.01',
      times_drafted: 74,
      high: 114,
      low: 179,
      stdev: 17.4,
      bye: 6,
    },
    {
      player_id: 5564,
      name: 'Sam LaPorta',
      position: 'TE',
      team: 'DET',
      adp: 155.5,
      adp_formatted: '12.02',
      times_drafted: 141,
      high: 100,
      low: 206,
      stdev: 22.0,
      bye: 5,
    },
    {
      player_id: 5648,
      name: 'Brock Purdy',
      position: 'QB',
      team: 'SF',
      adp: 155.8,
      adp_formatted: '12.02',
      times_drafted: 107,
      high: 98,
      low: 206,
      stdev: 21.9,
      bye: 9,
    },
    {
      player_id: 5277,
      name: 'Greg Dulcich',
      position: 'TE',
      team: 'DEN',
      adp: 156.8,
      adp_formatted: '12.03',
      times_drafted: 90,
      high: 117,
      low: 182,
      stdev: 16.3,
      bye: 14,
    },
    {
      player_id: 4893,
      name: 'Donovan Peoples-Jones',
      position: 'WR',
      team: 'DET',
      adp: 157.7,
      adp_formatted: '12.04',
      times_drafted: 103,
      high: 121,
      low: 180,
      stdev: 14.0,
      bye: 5,
    },
    {
      player_id: 4892,
      name: 'Jordan Love',
      position: 'QB',
      team: 'GB',
      adp: 158.2,
      adp_formatted: '12.04',
      times_drafted: 96,
      high: 97,
      low: 207,
      stdev: 23.2,
      bye: 10,
    },
    {
      player_id: 5617,
      name: 'Jerome Ford',
      position: 'RB',
      team: 'CLE',
      adp: 158.9,
      adp_formatted: '12.05',
      times_drafted: 82,
      high: 122,
      low: 179,
      stdev: 14.1,
      bye: 10,
    },
    {
      player_id: 1324,
      name: 'Pittsburgh Defense',
      position: 'DEF',
      team: 'PIT',
      adp: 159.6,
      adp_formatted: '12.06',
      times_drafted: 144,
      high: 112,
      low: 197,
      stdev: 19.1,
      bye: 9,
    },
    {
      player_id: 5471,
      name: 'Kenny Pickett',
      position: 'QB',
      team: 'PIT',
      adp: 160.2,
      adp_formatted: '12.06',
      times_drafted: 117,
      high: 92,
      low: 209,
      stdev: 25.9,
      bye: 9,
    },
    {
      player_id: 2906,
      name: 'Mike Gesicki',
      position: 'TE',
      team: 'NE',
      adp: 160.6,
      adp_formatted: '12.07',
      times_drafted: 38,
      high: 92,
      low: 207,
      stdev: 26.1,
      bye: 14,
    },
    {
      player_id: 2987,
      name: 'Marquez Valdes-Scantling',
      position: 'WR',
      team: 'KC',
      adp: 162.8,
      adp_formatted: '12.09',
      times_drafted: 62,
      high: 129,
      low: 180,
      stdev: 12.6,
      bye: 6,
    },
    {
      player_id: 5125,
      name: 'K.J. Osborn',
      position: 'WR',
      team: 'MIN',
      adp: 163.0,
      adp_formatted: '12.09',
      times_drafted: 70,
      high: 127,
      low: 180,
      stdev: 13.6,
      bye: 6,
    },
    {
      player_id: 1774,
      name: 'Graham Gano',
      position: 'PK',
      team: 'CAR',
      adp: 163.1,
      adp_formatted: '12.09',
      times_drafted: 55,
      high: 96,
      low: 203,
      stdev: 25.5,
      bye: 11,
    },
    {
      player_id: 5588,
      name: "Wan'Dale Robinson",
      position: 'WR',
      team: 'NYG',
      adp: 163.5,
      adp_formatted: '12.09',
      times_drafted: 33,
      high: 131,
      low: 191,
      stdev: 12.2,
      bye: 11,
    },
    {
      player_id: 4901,
      name: 'Chase Claypool',
      position: 'WR',
      team: 'MIA',
      adp: 164.0,
      adp_formatted: '12.10',
      times_drafted: 69,
      high: 140,
      low: 182,
      stdev: 10.7,
      bye: 6,
    },
    {
      player_id: 5031,
      name: 'Joshua Kelley',
      position: 'RB',
      team: 'LAC',
      adp: 164.1,
      adp_formatted: '12.10',
      times_drafted: 53,
      high: 129,
      low: 194,
      stdev: 13.4,
      bye: 5,
    },
    {
      player_id: 2433,
      name: 'Leonard Fournette',
      position: 'RB',
      team: 'BUF',
      adp: 164.4,
      adp_formatted: '12.10',
      times_drafted: 48,
      high: 131,
      low: 199,
      stdev: 15.5,
      bye: 12,
    },
    {
      player_id: 2130,
      name: 'Allen Robinson',
      position: 'WR',
      team: 'PIT',
      adp: 164.5,
      adp_formatted: '12.10',
      times_drafted: 40,
      high: 138,
      low: 180,
      stdev: 10.0,
      bye: 9,
    },
    {
      player_id: 1316,
      name: 'Miami Defense',
      position: 'DEF',
      team: 'MIA',
      adp: 165.1,
      adp_formatted: '12.11',
      times_drafted: 78,
      high: 121,
      low: 192,
      stdev: 16.7,
      bye: 6,
    },
    {
      player_id: 5686,
      name: 'Jalin Hyatt',
      position: 'WR',
      team: 'NYG',
      adp: 165.5,
      adp_formatted: '12.12',
      times_drafted: 54,
      high: 119,
      low: 210,
      stdev: 24.1,
      bye: 11,
    },
    {
      player_id: 5584,
      name: 'Justyn Ross',
      position: 'WR',
      team: 'KC',
      adp: 166.5,
      adp_formatted: '12.13',
      times_drafted: 34,
      high: 122,
      low: 206,
      stdev: 20.0,
      bye: 6,
    },
    {
      player_id: 2954,
      name: 'Jason Sanders',
      position: 'PK',
      team: 'MIA',
      adp: 167.2,
      adp_formatted: '12.13',
      times_drafted: 106,
      high: 117,
      low: 201,
      stdev: 19.1,
      bye: 6,
    },
    {
      player_id: 1315,
      name: 'Kansas City Defense',
      position: 'DEF',
      team: 'KC',
      adp: 167.9,
      adp_formatted: '12.14',
      times_drafted: 39,
      high: 119,
      low: 202,
      stdev: 18.8,
      bye: 6,
    },
    {
      player_id: 1331,
      name: 'Washington Defense',
      position: 'DEF',
      team: 'WAS',
      adp: 168.9,
      adp_formatted: '13.01',
      times_drafted: 52,
      high: 110,
      low: 209,
      stdev: 22.3,
      bye: 14,
    },
    {
      player_id: 4877,
      name: 'Zack Moss',
      position: 'RB',
      team: 'IND',
      adp: 170.5,
      adp_formatted: '13.02',
      times_drafted: 82,
      high: 127,
      low: 203,
      stdev: 17.8,
      bye: 14,
    },
    {
      player_id: 2424,
      name: 'Jason Myers',
      position: 'PK',
      team: 'SEA',
      adp: 170.9,
      adp_formatted: '13.03',
      times_drafted: 59,
      high: 115,
      low: 210,
      stdev: 21.4,
      bye: 10,
    },
    {
      player_id: 1960,
      name: 'Greg Zuerlein',
      position: 'PK',
      team: 'NYJ',
      adp: 171.1,
      adp_formatted: '13.03',
      times_drafted: 74,
      high: 113,
      low: 204,
      stdev: 22.2,
      bye: 12,
    },
    {
      player_id: 2724,
      name: 'Taysom Hill',
      position: 'TE',
      team: 'NO',
      adp: 173.6,
      adp_formatted: '13.06',
      times_drafted: 31,
      high: 115,
      low: 202,
      stdev: 22.3,
      bye: 12,
    },
  ],
};
